let db;
const main=document.getElementById('main'), search=document.getElementById('search');
const fmt=n=>new Intl.NumberFormat('es-ES').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const poster=(url,cls='poster')=>url?`<img class="${cls}" src="${esc(url)}" loading="lazy" onerror="this.outerHTML='<div class=\"${cls} missing\">▣</div>'">`:`<div class="${cls} missing">▣</div>`;
const shell=c=>{main.innerHTML=c;window.scrollTo({top:0,behavior:'instant'})};
function setNav(v){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.body.classList.remove('menu-open')}
function card(x,type){return `<article class="card" onclick="openDetail(${x.id},'${type}')" title="${esc(x.name)}">${poster(x.poster_url)}<div class="card-body"><div class="title">${esc(x.name)}</div><div class="meta">${x.year||'Sin año'}</div><div class="type-badge">${type==='movie'?'Película':'Serie'}</div></div></article>`}
function pager(page,pages,fn){if(pages<2)return '';return `<div class="pager"><button ${page<=1?'disabled':''} onclick="${fn}(${page-1})">← Anterior</button><span>Página ${page} de ${pages}</span><button ${page>=pages?'disabled':''} onclick="${fn}(${page+1})">Siguiente →</button></div>`}
function list(type,page=1,cat=''){setNav(type==='movie'?'movies':'series');const all=(type==='movie'?db.movies:db.series).filter(x=>!cat||x.category_ids.includes(Number(cat)));const size=40, pages=Math.max(1,Math.ceil(all.length/size)), items=all.slice((page-1)*size,page*size);const cats=db.categories.filter(c=>c.content_type===type);shell(`<div class="toolbar"><div><div class="eyebrow">Biblioteca</div><h1>${type==='movie'?'Películas':'Series'}</h1><p class="sub">${fmt(all.length)} títulos en esta vista de preview</p></div><select onchange="list('${type}',1,this.value)"><option value="">Todas las categorías</option>${cats.map(c=>`<option value="${c.id}" ${String(c.id)===String(cat)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="grid">${items.map(x=>card(x,type)).join('')}</div>${items.length?'':'<div class="empty">No hay resultados para este filtro.</div>'}${pager(page,pages,`(p)=>list('${type}',p,'${cat}')`)}`)}
function home(){setNav('home');shell(`<section class="hero"><div class="hero-copy"><div class="eyebrow">Preview sobre catálogo real</div><h1>Todo tu catálogo, en un solo lugar.</h1><p>Esta es una vista temporal de la interfaz de IPTV Manager. Los datos proceden de la BD persistente real; las URLs de reproducción se excluyen deliberadamente de esta preview.</p><div class="hero-actions"><button class="primary" onclick="list('movie')">Explorar películas</button><button class="secondary" onclick="list('series')">Explorar series</button></div></div></section><div class="stats"><div class="stat"><span class="stat-icon">▣</span><b>${fmt(db.stats.movies)}</b><span>Películas</span></div><div class="stat"><span class="stat-icon">▤</span><b>${fmt(db.stats.series)}</b><span>Series</span></div><div class="stat"><span class="stat-icon">◇</span><b>${fmt(db.stats.episodes)}</b><span>Episodios</span></div><div class="stat"><span class="stat-icon">◈</span><b>${fmt(db.stats.versions)}</b><span>Versiones</span></div></div><section><div class="section-head"><h2>Películas</h2><button class="text-button" onclick="list('movie')">Ver todo →</button></div><div class="rail">${db.movies.slice(0,12).map(x=>card(x,'movie')).join('')}</div></section><section><div class="section-head"><h2>Series</h2><button class="text-button" onclick="list('series')">Ver todo →</button></div><div class="rail">${db.series.slice(0,12).map(x=>card(x,'series')).join('')}</div></section>`)}
function categories(){setNav('categories');const movies=db.categories.filter(c=>c.content_type==='movie'),series=db.categories.filter(c=>c.content_type==='series');const render=(arr,type)=>arr.map(c=>`<button class="category" onclick="list('${type}',1,'${c.id}')"><strong>${esc(c.name)}</strong><small>${esc([c.quality,c.resolution,c.dynamic_range,c.audio,c.subtitles,c.language_hint].filter(Boolean).join(' · ')||'Explorar categoría')} →</small></button>`).join('');shell(`<div class="eyebrow">Organización</div><h1>Categorías</h1><p class="sub">${fmt(db.categories.length)} categorías seleccionadas.</p><h2>Películas</h2><div class="category-list">${render(movies,'movie')}</div><h2>Series</h2><div class="category-list">${render(series,'series')}</div>`)}
function searchCatalog(){const q=search.value.trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(q.length<2)return;const results=[...db.movies.map(x=>({...x,_type:'movie'})),...db.series.map(x=>({...x,_type:'series'}))].filter(x=>x.name.toLowerCase().includes(q));setNav('');shell(`<button class="back" onclick="home()">← Inicio</button><div class="eyebrow">Búsqueda</div><h1>Resultados para «${esc(search.value.trim())}»</h1><p class="sub">${fmt(results.length)} coincidencias en esta preview</p><div class="grid">${results.map(x=>card(x,x._type)).join('')}</div>${results.length?'':'<div class="empty">No se encontraron resultados.</div>'}`)}
function openDetail(id,type){const x=(type==='movie'?db.movies:db.series).find(v=>v.id===id);if(!x)return;if(type==='movie'){shell(`<button class="back" onclick="list('movie')">← Películas</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><div class="eyebrow">Película</div><h1>${esc(x.name)}</h1><div class="meta">${x.year||'Año desconocido'}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p><div class="tags">${(x.categories||[]).map(c=>`<span class="chip">${esc(c.name)}</span>`).join('')}</div><h2>Fuentes disponibles</h2><div class="versions">${(x.versions||[]).map(version).join('')||'<div class="empty">Sin datos de fuentes en la preview.</div>'}</div></div></section>`);return}shell(`<button class="back" onclick="list('series')">← Series</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><div class="eyebrow">Serie</div><h1>${esc(x.name)}</h1><div class="meta">${x.year||'Año desconocido'}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p><div class="tags">${(x.categories||[]).map(c=>`<span class="chip">${esc(c.name)}</span>`).join('')}</div>${(x.seasons||[]).map(s=>`<section class="season"><div class="season-head"><span>Temporada ${s.season_number}</span><span class="season-count">${s.episodes.length} episodios</span></div><div class="episodes">${s.episodes.map(e=>`<div class="episode"><span class="epno">E${String(e.episode_number).padStart(2,'0')}</span><span class="episode-title">${esc(e.title)}</span><span class="chip">${e.version_count} fuentes</span></div>`).join('')}</div></section>`).join('')||'<div class="empty">No hay temporadas disponibles en la muestra.</div>'}</div></section>`)}
function version(v){const labels=[v.quality,v.resolution,v.dynamic_range,v.video_codec,v.audio_codec,v.language,v.languages,v.subtitles].filter(Boolean);return `<div class="version"><div><div class="version-label-text">${esc(v.label||v.category_name||'Fuente')}</div>${labels.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><span class="chip">Preview</span></div>`}
async function init(){try{const r=await fetch('preview-data.json');db=await r.json();home()}catch(e){shell(`<div class="empty">No se pudo cargar la preview: ${esc(e.message)}</div>`)}}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>b.dataset.view==='home'?home():b.dataset.view==='movies'?list('movie'):b.dataset.view==='series'?list('series'):categories());document.getElementById('mobileMenu').onclick=()=>document.body.classList.toggle('menu-open');document.getElementById('searchBtn').onclick=searchCatalog;search.addEventListener('keydown',e=>{if(e.key==='Enter')searchCatalog()});Object.assign(window,{home,list,categories,openDetail,searchCatalog});init();
