let manifest,cats,main=document.getElementById('main'),search=document.getElementById('search');const cache=new Map();const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=n=>new Intl.NumberFormat('es-ES').format(n||0);const img=(u,c='poster')=>u?`<img class="${c}" src="${esc(u)}" loading="lazy">`:`<div class="${c} missing">▣</div>`;
async function get(u){if(cache.has(u))return cache.get(u);const r=await fetch(u);if(!r.ok)throw Error(u);const d=await r.json();cache.set(u,d);return d}
async function allPages(t){const n=t==='movie'?manifest.movie_pages:manifest.series_pages,a=[];for(let i=1;i<=n;i++){const d=await get(`data/${t==='movie'?'movies':'series'}/page-${String(i).padStart(3,'0')}.json`);a.push(...d.items)}return a}
async function detail(id,t){const p=t==='movie'?'movies':'series',idx=await get(`data/details/${p}/index.json`),n=idx.items[String(id)];if(!n)return null;const d=await get(`data/details/${p}/chunk-${String(n).padStart(3,'0')}.json`);return d[String(id)]}
function nav(v){document.querySelectorAll('.topnav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
function card(x,t){return `<article class="card" onclick="openDetail(${x.id},'${t}')">${img(x.poster_url)}<div class="ct"><strong>${esc(x.name)}</strong><small>${x.year||''}</small></div></article>`}
function rail(title,items,t){return `<section class="rail-section"><div class="rail-title"><h2>${title}</h2><button onclick="list('${t}')">Ver todo</button></div><div class="rail">${items.map(x=>card(x,t)).join('')}</div></section>`}
async function home(){nav('home');const [m,s]=await Promise.all([get('data/movies/page-001.json'),get('data/series/page-001.json')]);main.innerHTML=`<section class="hero"><div class="hero-copy"><span class="eyebrow">CATÁLOGO REAL · PREVIEW</span><h1>Tu biblioteca, como en Google TV.</h1><p>${fmt(manifest.stats.movies)} películas · ${fmt(manifest.stats.series)} series · ${fmt(manifest.stats.episodes)} episodios</p><button class="cta" onclick="list('movie')">Explorar biblioteca</button></div></section><div class="stats">${[['movies','Películas'],['series','Series'],['episodes','Episodios'],['versions','Versiones']].map(([k,l])=>`<div><b>${fmt(manifest.stats[k])}</b><span>${l}</span></div>`).join('')}</div>${rail('Películas',m.items.slice(0,15),'movie')}${rail('Series',s.items.slice(0,15),'series')}<section class="rail-section"><div class="rail-title"><h2>Categorías</h2><button onclick="categories()">Ver todo</button></div><div class="chips">${cats.slice(0,14).map(c=>`<button onclick="list('${c.content_type}',1,${c.id})">${esc(c.name)}</button>`).join('')}</div></section>`}
async function list(t,page=1,cat=''){nav(t==='movie'?'movies':'series');const d=await get(`data/${t==='movie'?'movies':'series'}/page-${String(page).padStart(3,'0')}.json`);const items=cat?d.items.filter(x=>x.categories.some(c=>c.id===Number(cat))):d.items,opts=cats.filter(c=>c.content_type===t);main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Biblioteca</span><h1>${t==='movie'?'Películas':'Series'}</h1><p>${fmt(d.total)} títulos</p></div><select onchange="list('${t}',1,this.value)"><option value="">Todas las categorías</option>${opts.map(c=>`<option value="${c.id}" ${String(cat)===String(c.id)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="grid">${items.map(x=>card(x,t)).join('')}</div><div class="pager"><button ${page<=1?'disabled':''} onclick="list('${t}',${page-1},'${cat}')">‹</button><span>${page} / ${d.pages}</span><button ${page>=d.pages?'disabled':''} onclick="list('${t}',${page+1},'${cat}')">›</button></div>`}
async function categories(){nav('categories');main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Biblioteca</span><h1>Categorías</h1><p>${cats.length} categorías</p></div></div><div class="category-grid">${cats.map(c=>`<button onclick="list('${c.content_type}',1,${c.id})"><strong>${esc(c.name)}</strong><small>${esc([c.quality,c.resolution,c.dynamic_range,c.audio,c.subtitles,c.language_hint].filter(Boolean).join(' · ')||'Explorar')}</small></button>`).join('')}</div>`}
async function openDetail(id,t){const x=await detail(id,t);if(!x)return;nav(t==='movie'?'movies':'series');let body=`<div class="detail"><div>${img(x.poster_url,'detail-poster')}</div><div><span class="eyebrow">${t==='movie'?'PELÍCULA':'SERIE'}</span><h1>${esc(x.title)}</h1><p class="detail-meta">${x.year||''}</p><p class="overview">${esc(x.overview||'Sin descripción disponible.')}</p><div class="chips">${(x.categories||[]).slice(0,12).map(c=>`<span>${esc(c.name)}</span>`).join('')}</div>`;if(t==='movie')body+=`<h2>Versiones disponibles</h2><div class="versions">${(x.versions||[]).map(version).join('')||'<div class="empty">Sin versiones.</div>'}</div>`;else body+=`<div class="seasons">${(x.seasons||[]).map(s=>`<section class="season"><h2>Temporada ${s.season_number} <small>${s.episodes.length} episodios</small></h2>${s.episodes.map(e=>`<article class="episode">${img(e.poster_url,'ep-poster')}<div><b>E${String(e.episode_number).padStart(2,'0')} · ${esc(e.title)}</b><p>${esc(e.overview||'')}</p><button onclick="episodeSources(${e.id})">Fuentes (${(e.versions||[]).length})</button></div></article>`).join('')}</section>`).join('')}</div>`;main.innerHTML=`<button class="back" onclick="list('${t}')">← Volver</button>${body}</div></div>`}
function version(v){const tags=[v.quality,v.resolution,v.dynamic_range,v.video_codec,v.audio_codec,v.language,v.subtitles].filter(Boolean);return `<div class="version"><div><b>${esc(v.label||v.category_name||'Fuente')}</b><div class="chips">${tags.map(t=>`<span>${esc(t)}</span>`).join('')}<span>${v.stream_count||0} streams</span></div></div><button class="cta small" disabled>Reproducir</button></div>`}
async function episodeSources(id){const idx=await get('data/details/series/index.json'),n=idx.items[String(id)],d=await get(`data/details/series/chunk-${String(n).padStart(3,'0')}.json`);let ep=null;for(const s of Object.values(d)){for(const season of s.seasons||[]){ep=season.episodes.find(e=>e.id===id);if(ep)break}if(ep)break}if(!ep)return;document.body.insertAdjacentHTML('beforeend',`<div class="modal" onclick="this.remove()"><div class="modal-box" onclick="event.stopPropagation()"><button class="close" onclick="this.closest('.modal').remove()">×</button><span class="eyebrow">FUENTES</span><h2>${esc(ep.title)}</h2>${(ep.versions||[]).map(version).join('')}</div></div>`)}
async function searchCatalog(){const q=search.value.trim().toLocaleLowerCase();if(q.length<2)return;const [m,s]=await Promise.all([allPages('movie'),allPages('series')]),r=[...m.map(x=>({...x,_type:'movie'})),...s.map(x=>({...x,_type:'series'}))].filter(x=>(x.name||'').toLocaleLowerCase().includes(q)||(x.original_title||'').toLocaleLowerCase().includes(q));nav('');main.innerHTML=`<div class="page-head"><div><span class="eyebrow">Búsqueda</span><h1>Resultados</h1><p>${fmt(r.length)} coincidencias para «${esc(q)}»</p></div></div><div class="grid">${r.map(x=>card(x,x._type)).join('')}</div>`}
async function init(){try{manifest=await get('data/manifest.json');cats=await get('data/categories.json');await home()}catch(e){main.innerHTML=`<div class="empty">Error cargando el catálogo: ${esc(e.message)}</div>`}}
document.querySelectorAll('.topnav button').forEach(b=>b.onclick=()=>b.dataset.view==='home'?home():b.dataset.view==='movies'?list('movie'):b.dataset.view==='series'?list('series'):categories());document.getElementById('searchBtn').onclick=searchCatalog;search.addEventListener('keydown',e=>{if(e.key==='Enter')searchCatalog()});document.getElementById('mobileMenu').onclick=()=>document.body.classList.toggle('menu-open');Object.assign(window,{home,list,categories,openDetail,episodeSources});init();
