const API='/api';
const main=document.getElementById('main'), search=document.getElementById('search'), searchBtn=document.getElementById('searchBtn'), health=document.getElementById('health');
const fmt=n=>new Intl.NumberFormat('es-ES').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const poster=(url,cls='poster')=>url?`<img class="${cls}" src="${esc(url)}" loading="lazy" onerror="this.outerHTML='<div class=\"${cls} missing\">▣</div>'">`:`<div class="${cls} missing">▣</div>`;
const loading=t=>`<div class="loading"><span class="spinner"></span>${esc(t)}</div>`;
async function get(url){const r=await fetch(API+url);if(!r.ok)throw new Error(await r.text());return r.json()}
function setNav(v){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v));document.body.classList.remove('menu-open')}
function shell(c){main.innerHTML=c;window.scrollTo({top:0,behavior:'instant'})}
function pager(data,fn){if(!data.pages||data.pages<2)return '';return `<div class="pager"><button ${data.page<=1?'disabled':''} onclick="${fn}(${data.page-1})">← Anterior</button><span>Página ${data.page} de ${data.pages}</span><button ${data.page>=data.pages?'disabled':''} onclick="${fn}(${data.page+1})">Siguiente →</button></div>`}
function card(x,type){return `<article class="card" onclick="${type==='movie'?'openMovie':'openSeries'}(${x.id})" title="${esc(x.name)}">${poster(x.poster_url)}<div class="card-body"><div class="title">${esc(x.name)}</div><div class="meta">${x.year||'Sin año'}</div><div class="type-badge">${type==='movie'?'Película':'Serie'}</div></div></article>`}
function version(v){const labels=[v.quality,v.resolution,v.dynamic_range,v.video_codec,v.audio_codec,v.language,v.languages,v.subtitles].filter(Boolean);return `<div class="version"><div><div class="version-label-text">${esc(v.label||v.category_name||'Fuente')}</div>${labels.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div><div>${(v.streams||[]).map(s=>s.playback_url?`<a class="play" href="${esc(s.playback_url)}" target="_blank" rel="noopener">▶ Reproducir</a>`:'').join('')}</div></div>`}
async function home(){setNav('home');shell(loading('Cargando biblioteca…'));try{const [s,movies,series]=await Promise.all([get('/stats'),get('/catalog/movie?page=1&page_size=12'),get('/catalog/series?page=1&page_size=12')]);shell(`<section class="hero"><div class="hero-copy"><div class="eyebrow">Tu biblioteca IPTV</div><h1>Todo tu catálogo, en un solo lugar.</h1><p>Explora películas y series desde la base de datos local. Las fuentes y versiones se consultan solo cuando abres un título.</p><div class="hero-actions"><button class="primary" onclick="list('movie',1)">Explorar películas</button><button class="secondary" onclick="list('series',1)">Explorar series</button></div></div></section><div class="stats"><div class="stat"><span class="stat-icon">▣</span><b>${fmt(s.movies)}</b><span>Películas</span></div><div class="stat"><span class="stat-icon">▤</span><b>${fmt(s.series)}</b><span>Series</span></div><div class="stat"><span class="stat-icon">◇</span><b>${fmt(s.episodes)}</b><span>Episodios</span></div><div class="stat"><span class="stat-icon">◈</span><b>${fmt(s.versions)}</b><span>Versiones</span></div></div><section><div class="section-head"><h2>Películas</h2><button class="text-button" onclick="list('movie',1)">Ver todo →</button></div><div class="rail">${movies.items.map(x=>card(x,'movie')).join('')}</div></section><section><div class="section-head"><h2>Series</h2><button class="text-button" onclick="list('series',1)">Ver todo →</button></div><div class="rail">${series.items.map(x=>card(x,'series')).join('')}</div></section>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function list(type,page=1,categoryId=''){setNav(type==='movie'?'movies':'series');shell(loading('Cargando biblioteca…'));try{const cats=await get('/categories?content_type='+type);const data=await get(`/catalog/${type}?page=${page}&page_size=40${categoryId?'&category_id='+categoryId:''}`);shell(`<div class="toolbar"><div><div class="eyebrow">Biblioteca</div><h1>${type==='movie'?'Películas':'Series'}</h1><p class="sub">${fmt(data.total)} títulos disponibles</p></div><select onchange="list('${type}',1,this.value)" aria-label="Filtrar por categoría"><option value="">Todas las categorías</option>${cats.map(c=>`<option value="${c.id}" ${String(c.id)===String(categoryId)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="grid">${data.items.map(x=>card(x,type)).join('')}</div>${data.items.length?'': '<div class="empty">No hay resultados para este filtro.</div>'}${pager(data,`(p)=>list('${type}',p,'${categoryId}')`)}`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function categories(){setNav('categories');shell(loading('Cargando categorías…'));try{const cats=await get('/categories');const movies=cats.filter(c=>c.content_type==='movie'),series=cats.filter(c=>c.content_type==='series');shell(`<div class="eyebrow">Organización</div><h1>Categorías</h1><p class="sub">${fmt(cats.length)} categorías seleccionadas en el catálogo.</p><h2>Películas</h2><div class="category-list">${movies.map(c=>category(c,'movie')).join('')}</div><h2>Series</h2><div class="category-list">${series.map(c=>category(c,'series')).join('')}</div>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
function category(c,type){const detail=[c.quality,c.resolution,c.dynamic_range,c.audio,c.subtitles,c.language_hint].filter(Boolean).join(' · ');return `<button class="category" onclick="list('${type}',1,'${c.id}')"><strong>${esc(c.name)}</strong><small>${esc(detail||'Explorar categoría')} →</small></button>`}
async function searchCatalog(page=1){const q=search.value.trim();if(q.length<2){search.focus();return}setNav('');shell(loading('Buscando en la biblioteca…'));try{const data=await get(`/search?q=${encodeURIComponent(q)}&page=${page}&page_size=40`);shell(`<button class="back" onclick="home()">← Inicio</button><div class="eyebrow">Búsqueda</div><h1>Resultados para «${esc(q)}»</h1><p class="sub">${fmt(data.total)} coincidencias</p><div class="grid">${data.items.map(x=>card(x,x.content_type)).join('')}</div>${data.items.length?'':'<div class="empty">No se encontraron resultados.</div>'}${pager(data,'searchCatalog')}`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function openMovie(id){shell(loading('Cargando película…'));try{const x=await get('/movies/'+id);shell(`<button class="back" onclick="list('movie',1)">← Películas</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><div class="eyebrow">Película</div><h1>${esc(x.title)}</h1><div class="meta">${x.year||'Año desconocido'}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p><div class="tags">${(x.categories||[]).map(c=>`<span class="chip">${esc(c.name)}</span>`).join('')}</div><h2>Fuentes disponibles</h2><div class="versions">${(x.versions||[]).map(version).join('')||'<div class="empty">No hay streams activos.</div>'}</div></div></section>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function openSeries(id){shell(loading('Cargando serie…'));try{const x=await get('/series/'+id);shell(`<button class="back" onclick="list('series',1)">← Series</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><div class="eyebrow">Serie</div><h1>${esc(x.title)}</h1><div class="meta">${x.year||'Año desconocido'}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p><div class="tags">${(x.categories||[]).map(c=>`<span class="chip">${esc(c.name)}</span>`).join('')}</div>${(x.seasons||[]).map(s=>`<section class="season"><div class="season-head"><span>Temporada ${s.season_number}</span><span class="season-count">${(s.episodes||[]).length} episodios</span></div><div class="episodes">${(s.episodes||[]).map(e=>`<div class="episode"><span class="epno">E${String(e.episode_number).padStart(2,'0')}</span><span class="episode-title">${esc(e.title)}${e.air_date?`<small class="episode-date">${esc(e.air_date)}</small>`:''}</span><button class="play" onclick="showEpisode(${e.id})">${(e.versions||[]).length?'Fuentes':'Sin fuente'}</button></div>`).join('')}</div></section>`).join('')||'<div class="empty">No hay temporadas disponibles.</div>'}</div></section>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function showEpisode(id){try{const e=await get('/episodes/'+id);const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-box"><button class="back" id="close">✕ Cerrar</button><div class="eyebrow">Episodio</div><h2>${esc(e.title)}</h2><p class="description">${esc(e.overview||'')}</p><div class="versions">${(e.versions||[]).map(version).join('')||'<div class="empty">No hay fuentes.</div>'}</div></div>`;document.body.appendChild(modal);modal.querySelector('#close').onclick=()=>modal.remove();modal.onclick=x=>{if(x.target===modal)modal.remove()};document.addEventListener('keydown',function close(ev){if(ev.key==='Escape'){modal.remove();document.removeEventListener('keydown',close)}})}catch(e){alert(e.message)}}
searchBtn.onclick=()=>searchCatalog(1);search.addEventListener('keydown',e=>{if(e.key==='Enter')searchCatalog(1)});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>b.dataset.view==='home'?home():b.dataset.view==='movies'?list('movie',1):b.dataset.view==='series'?list('series',1):categories());document.getElementById('mobileMenu').onclick=()=>document.body.classList.toggle('menu-open');
(async()=>{try{const h=await get('/health');health.innerHTML=`<i></i><span>API conectada · ${esc(h.version||'')}</span>`;health.classList.add('ok')}catch(e){health.innerHTML='<i></i><span>API no disponible</span>'}home()})();
Object.assign(window,{home,list,categories,openMovie,openSeries,showEpisode,searchCatalog});
