const API='/api';
const main=document.getElementById('main');
const search=document.getElementById('search');
const searchBtn=document.getElementById('searchBtn');
const health=document.getElementById('health');
const fmt=n=>new Intl.NumberFormat('es-ES').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const poster=(url,cls='poster')=>url?`<img class="${cls}" src="${esc(url)}" loading="lazy" onerror="this.style.display='none'">`:`<div class="${cls} missing">${cls.includes('hero')?'🎬':'▧'}</div>`;
async function get(url){const r=await fetch(API+url);if(!r.ok)throw new Error(await r.text());return r.json()}
function setNav(view){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===view));}
function shell(content){main.innerHTML=content}
function version(v){const labels=[v.quality,v.resolution,v.dynamic_range,v.audio_codec,v.language,v.languages,v.subtitles].filter(x=>x!==null&&x!==undefined&&x!==''&&x!=='None');return `<div class="version"><div class="version-main"><strong>${esc(v.label||'Fuente')}</strong>${labels.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${(v.streams||[]).map(s=>s.playback_url?`<a class="play" href="${esc(s.playback_url)}" target="_blank" rel="noopener">▶ Reproducir</a>`:'').join('')}</div>`}
function movieCard(x){return `<article class="card" onclick="openMovie(${x.id})">${poster(x.poster_url)}<div class="card-body"><div class="title">${esc(x.name)}</div><div class="meta">${x.year||'—'}</div></div></article>`}
function seriesCard(x){return `<article class="card" onclick="openSeries(${x.id})">${poster(x.poster_url)}<div class="card-body"><div class="title">${esc(x.name)}</div><div class="meta">Serie${x.year?' · '+x.year:''}</div></div></article>`}
async function home(){setNav('home');shell('<div class="loading">Cargando…</div>');try{const s=await get('/stats');shell(`<h1>Tu catálogo</h1><p class="sub">Una vista unificada de las películas y series sincronizadas.</p><div class="stats"><div class="stat"><b>${fmt(s.movies)}</b><span>Películas</span></div><div class="stat"><b>${fmt(s.series)}</b><span>Series</span></div><div class="stat"><b>${fmt(s.episodes)}</b><span>Episodios</span></div><div class="stat"><b>${fmt(s.versions)}</b><span>Versiones</span></div></div><h2>Buscar contenido</h2><p class="sub">Usa el buscador superior para localizar una película o serie y elegir su fuente.</p>`)}catch(e){shell(`<div class="empty">No se pudo cargar el catálogo.<br>${esc(e.message)}</div>`)}}
async function list(type){setNav(type==='movie'?'movies':'series');shell('<div class="loading">Cargando categorías…</div>');try{const cats=await get('/categories?content_type='+type);shell(`<h1>${type==='movie'?'Películas':'Series'}</h1><p class="sub">Selecciona una categoría para consultar su contenido.</p><div class="category-list">${cats.map(c=>`<div class="category"><span>${esc(c.name)}</span><small>${c.quality||''} ${c.resolution||''}</small></div>`).join('')}</div><div class="notice">La navegación por categoría está preparada en la API. La primera interfaz mantiene esta vista ligera para no cargar miles de registros innecesariamente.</div>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function categories(){setNav('categories');shell('<div class="loading">Cargando…</div>');try{const cats=await get('/categories');shell(`<h1>Categorías seleccionadas</h1><p class="sub">${cats.length} categorías forman actualmente el catálogo.</p><div class="category-list">${cats.map(c=>`<div class="category"><span>${esc(c.name)}</span><small>${esc(c.content_type)} · ${esc([c.quality,c.resolution,c.dynamic_range,c.audio,c.subtitles?'subtítulos':null,c.language_hint].filter(Boolean).join(' · '))}</small></div>`).join('')}</div>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function searchCatalog(){const q=search.value.trim();if(q.length<2)return;setNav('');shell(`<div class="loading">Buscando «${esc(q)}»…</div>`);try{const data=await get('/search?q='+encodeURIComponent(q)+'&limit=50');const movies=data.results.filter(x=>x.content_type==='movie'),series=data.results.filter(x=>x.content_type==='series');shell(`<button class="back" onclick="home()">← Inicio</button><h1>Resultados</h1><p class="sub">${data.results.length} resultados para «${esc(q)}»</p>${movies.length?`<h2>Películas</h2><div class="grid">${movies.map(movieCard).join('')}</div>`:''}${series.length?`<h2>Series</h2><div class="grid">${series.map(seriesCard).join('')}</div>`:''}${!data.results.length?'<div class="empty">No se encontraron resultados.</div>':''}`)}catch(e){shell(`<div class="empty">Error en la búsqueda: ${esc(e.message)}</div>`)}}
async function openMovie(id){shell('<div class="loading">Cargando película…</div>');try{const x=await get('/movies/'+id);shell(`<button class="back" onclick="searchCatalog()">← Volver</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><h1>${esc(x.title)}</h1><div class="meta">${x.year||''}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p><h2>Versiones disponibles</h2><div class="versions">${(x.versions||[]).map(version).join('')||'<div class="empty">No hay streams activos.</div>'}</div></div></section>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function openSeries(id){shell('<div class="loading">Cargando serie y episodios…</div>');try{const x=await get('/series/'+id);shell(`<button class="back" onclick="searchCatalog()">← Volver</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><h1>${esc(x.title)}</h1><div class="meta">${x.year||''}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p>${(x.seasons||[]).map(season=>`<section class="season"><div class="season-head">Temporada ${season.season_number}</div><div class="episodes">${(season.episodes||[]).map(ep=>`<div class="episode"><span class="epno">E${String(ep.episode_number).padStart(2,'0')}</span><span>${esc(ep.title)}</span><span>${(ep.versions||[]).length?`<button class="play" onclick="showEpisode(${ep.id})">Ver fuentes</button>`:'—'}</span></div>`).join('')}</div></section>`).join('')||'<div class="empty">No hay episodios.</div>'}</div></section>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function showEpisode(id){try{const ep=await get('/episodes/'+id);const html=(ep.versions||[]).map(version).join('')||'<div class="empty">No hay fuentes.</div>';const modal=document.createElement('div');modal.style='position:fixed;inset:0;background:rgba(0,0,0,.7);display:grid;place-items:center;padding:20px;z-index:20';modal.innerHTML=`<div style="max-width:760px;width:100%;background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:20px"><button class="back" id="close">✕ Cerrar</button><h2 style="margin-top:0">${esc(ep.title)}</h2><div class="versions">${html}</div></div>`;document.body.appendChild(modal);modal.querySelector('#close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()}}catch(e){alert(e.message)}}
searchBtn.onclick=searchCatalog;search.addEventListener('keydown',e=>{if(e.key==='Enter')searchCatalog()});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>b.dataset.view==='home'?home():b.dataset.view==='movies'?list('movie'):b.dataset.view==='series'?list('series'):categories());
(async()=>{try{const h=await get('/health');health.textContent='● API conectada';health.classList.add('ok')}catch(e){health.textContent='● API no disponible'}home()})();
window.home=home;window.openMovie=openMovie;window.openSeries=openSeries;window.showEpisode=showEpisode;window.searchCatalog=searchCatalog;
