const API='/api';
const main=document.getElementById('main'), search=document.getElementById('search'), searchBtn=document.getElementById('searchBtn'), health=document.getElementById('health');
const fmt=n=>new Intl.NumberFormat('es-ES').format(Number(n||0));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const poster=(url,cls='poster')=>url?`<img class="${cls}" src="${esc(url)}" loading="lazy" onerror="this.style.display='none'">`:`<div class="${cls} missing">🎬</div>`;
async function get(url){const r=await fetch(API+url);if(!r.ok)throw new Error(await r.text());return r.json()}
function setNav(v){document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
function shell(c){main.innerHTML=c}
function pager(data,fn){if(!data.pages||data.pages<2)return '';return `<div class="pager"><button ${data.page<=1?'disabled':''} onclick="${fn}(${data.page-1})">←</button><span>Página ${data.page} de ${data.pages}</span><button ${data.page>=data.pages?'disabled':''} onclick="${fn}(${data.page+1})">→</button></div>`}
function card(x,type){return `<article class="card" onclick="${type==='movie'?'openMovie':'openSeries'}(${x.id})">${poster(x.poster_url)}<div class="card-body"><div class="title">${esc(x.name)}</div><div class="meta">${x.year||'—'}</div></div></article>`}
function version(v){const labels=[v.quality,v.resolution,v.dynamic_range,v.video_codec,v.audio_codec,v.language,v.languages,v.subtitles].filter(Boolean);return `<div class="version"><div><strong>${esc(v.label||'Fuente')}</strong>${labels.map(x=>`<span class="chip">${esc(x)}</span>`).join('')}</div>${(v.streams||[]).map(s=>s.playback_url?`<a class="play" href="${esc(s.playback_url)}" target="_blank" rel="noopener">▶ Reproducir</a>`:'').join('')}</div>`}
async function home(){setNav('home');shell('<div class="loading">Cargando…</div>');try{const s=await get('/stats');shell(`<h1>Tu catálogo</h1><p class="sub">Biblioteca local de IPTV Manager.</p><div class="stats"><div class="stat"><b>${fmt(s.movies)}</b><span>Películas</span></div><div class="stat"><b>${fmt(s.series)}</b><span>Series</span></div><div class="stat"><b>${fmt(s.episodes)}</b><span>Episodios</span></div><div class="stat"><b>${fmt(s.versions)}</b><span>Versiones</span></div></div><div class="home-actions"><button onclick="list('movie',1)">🎬 Explorar películas</button><button onclick="list('series',1)">📺 Explorar series</button></div>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function list(type,page=1,categoryId=''){setNav(type==='movie'?'movies':'series');shell('<div class="loading">Cargando biblioteca…</div>');try{const cats=await get('/categories?content_type='+type);const data=await get(`/catalog/${type}?page=${page}&page_size=40${categoryId?'&category_id='+categoryId:''}`);shell(`<div class="toolbar"><div><h1>${type==='movie'?'Películas':'Series'}</h1><p class="sub">${fmt(data.total)} títulos</p></div><select onchange="list('${type}',1,this.value)"><option value="">Todas las categorías</option>${cats.map(c=>`<option value="${c.id}" ${String(c.id)===String(categoryId)?'selected':''}>${esc(c.name)}</option>`).join('')}</select></div><div class="grid">${data.items.map(x=>card(x,type)).join('')}</div>${data.items.length?'': '<div class="empty">No hay resultados.</div>'}${pager(data,`(p)=>list('${type}',p,'${categoryId}')`)}`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function searchCatalog(page=1){const q=search.value.trim();if(q.length<2)return;setNav('');shell('<div class="loading">Buscando…</div>');try{const data=await get(`/search?q=${encodeURIComponent(q)}&page=${page}&page_size=40`);const movies=data.items.filter(x=>x.content_type==='movie'), series=data.items.filter(x=>x.content_type==='series');shell(`<button class="back" onclick="home()">← Inicio</button><h1>Resultados</h1><p class="sub">${fmt(data.total)} resultados para «${esc(q)}»</p><div class="grid">${[...movies,...series].map(x=>card(x,x.content_type)).join('')}</div>${data.items.length?'':'<div class="empty">No se encontraron resultados.</div>'}${pager(data,'searchCatalog')}`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function openMovie(id){shell('<div class="loading">Cargando película…</div>');try{const x=await get('/movies/'+id);shell(`<button class="back" onclick="list('movie',1)">← Películas</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><h1>${esc(x.title)}</h1><div class="meta">${x.year||''}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p><div class="tags">${(x.categories||[]).map(c=>`<span class="chip">${esc(c.name)}</span>`).join('')}</div><h2>Fuentes disponibles</h2><div class="versions">${(x.versions||[]).map(version).join('')||'<div class="empty">No hay streams activos.</div>'}</div></div></section>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function openSeries(id){shell('<div class="loading">Cargando serie…</div>');try{const x=await get('/series/'+id);shell(`<button class="back" onclick="list('series',1)">← Series</button><section class="detail">${poster(x.poster_url,'hero-poster')}<div><h1>${esc(x.title)}</h1><div class="meta">${x.year||''}</div><p class="description">${esc(x.overview||'Sin descripción disponible.')}</p>${(x.seasons||[]).map(s=>`<section class="season"><div class="season-head">Temporada ${s.season_number}</div><div class="episodes">${(s.episodes||[]).map(e=>`<div class="episode"><span class="epno">E${String(e.episode_number).padStart(2,'0')}</span><span>${esc(e.title)}</span><button class="play" onclick="showEpisode(${e.id})">${(e.versions||[]).length?'Fuentes':'Sin fuente'}</button></div>`).join('')}</div></section>`).join('')}</div></section>`)}catch(e){shell(`<div class="empty">${esc(e.message)}</div>`)}}
async function showEpisode(id){try{const e=await get('/episodes/'+id);const modal=document.createElement('div');modal.className='modal';modal.innerHTML=`<div class="modal-box"><button class="back" id="close">✕ Cerrar</button><h2>${esc(e.title)}</h2><div class="versions">${(e.versions||[]).map(version).join('')||'<div class="empty">No hay fuentes.</div>'}</div></div>`;document.body.appendChild(modal);modal.querySelector('#close').onclick=()=>modal.remove();modal.onclick=x=>{if(x.target===modal)modal.remove()}}catch(e){alert(e.message)}}
searchBtn.onclick=()=>searchCatalog(1);search.addEventListener('keydown',e=>{if(e.key==='Enter')searchCatalog(1)});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>b.dataset.view==='home'?home():b.dataset.view==='movies'?list('movie',1):b.dataset.view==='series'?list('series',1):home());
(async()=>{try{await get('/health');health.textContent='● API conectada';health.classList.add('ok')}catch(e){health.textContent='● API no disponible'}home()})();
Object.assign(window,{home,list,openMovie,openSeries,showEpisode,searchCatalog});
